# variable -> 
--- 
 - name: install lemp stack in variable
   hosts: localhost
   become: yes
   vars: # define variables and assighn valiues
      web_sr: nginx # stoped nginx
      web_sr_2: httpd # install httpd
      db_sr: mariadb105-server
      php_sr: 
        - php
        - php-fpm
      web_service: nginx
      web_service_2: httpd
      db_service: mariadb 
      php_service: php-fpm 
      web_file_path: /var/www/html/index.php
   tasks:
    - name: install nginx package  # variable call
      ansible.builtin.dnf:
        name: "{{ web_sr }}"
        state: absent
    - name: install httpd package  # variable call
      ansible.builtin.dnf:
        name: "{{ web_sr_2 }}"
        state: present
    - name: install mariadb package
      ansible.builtin.dnf:
        name: "{{ db_sr }}"
        state: present
    - name: install php packeage 
      ansible.builtin.dnf:
        name: "{{ php_sr }}"
        state: present
    - name: start and enable nginx service
      ansible.builtin.systemd_service:
        name: "{{ web_service }}"
        state: stopped
        enabled: false
    - name: start and enable httpd service
      ansible.builtin.systemd_service:
        name: "{{ web_service_2 }}"
        state: started
        enabled: true
    - name: start and enabled mariadb service 
      ansible.builtin.systemd_service:
        name: "{{ db_service }}"
        state: started
        enabled: true
    - name: start and enable php-fpm service 
      ansible.builtin.systemd_service:
        name: "{{ php_service }}"
        state: started
        enabled: true
    - name: deploy index.php file
      ansible.builtin.copy:
        src: /home/ec2-user/index.php
        dest: "{{ web_file_path }}"
        owner: nginx
        group: nginx
        mode: '0644'
    
